SDK_FILES = \
	$(srcdir)/Penglai-sdk-TVM/enclave-driver/penglai.ko \
	$(srcdir)/Penglai-sdk-TVM/demo/host/host \
	$(srcdir)/Penglai-sdk-TVM/demo/host-measure/host-measure \
	$(srcdir)/Penglai-sdk-TVM/demo/fork-host/fork-host \
	$(srcdir)/Penglai-sdk-TVM/demo/hello-world/hello-world \
	$(srcdir)/Penglai-sdk-TVM/demo/case-1-introspection/case-inspector/case-inspector \
	$(srcdir)/Penglai-sdk-TVM/demo/case-1-introspection/case-inspectee/case-inspectee \
	$(srcdir)/Penglai-sdk-TVM/demo/case-2-sharing/case-share/case-share \
	$(srcdir)/Penglai-sdk-TVM/demo/case-2-sharing/case-sharee/case-sharee \
	$(srcdir)/Penglai-sdk-TVM/demo/case-2-sharing/case-sharee-plus/case-sharee-plus \
	$(srcdir)/Penglai-sdk-TVM/demo/case-2-sharing/case-sharer/case-sharer \
	$(srcdir)/Penglai-sdk-TVM/demo/case-3-migration/case-migratee/case-migratee \
	$(srcdir)/Penglai-sdk-TVM/demo/case-3-migration/case-migrator/case-migrator \
	$(srcdir)/Penglai-sdk-TVM/demo/eval-1-benchmark/rv8/aes/aes \
	$(srcdir)/Penglai-sdk-TVM/demo/eval-1-benchmark/rv8/dhrystone/dhrystone \
	$(srcdir)/Penglai-sdk-TVM/demo/eval-1-benchmark/rv8/norx/norx \
	$(srcdir)/Penglai-sdk-TVM/demo/eval-1-benchmark/rv8/primes/primes \
	$(srcdir)/Penglai-sdk-TVM/demo/eval-1-benchmark/rv8/qsort/qsort \
	$(srcdir)/Penglai-sdk-TVM/demo/eval-1-benchmark/rv8/sha512/sha512 \
	$(srcdir)/Penglai-sdk-TVM/demo/eval-1-benchmark/rv8-pe/rv8-pe \
	$(srcdir)/Penglai-sdk-TVM/demo/eval-3-cases/eval-inspectee/eval-inspectee \
	$(srcdir)/Penglai-sdk-TVM/demo/eval-3-cases/eval-inspector/eval-inspector \
	$(srcdir)/Penglai-sdk-TVM/demo/rv8-baseline/aes/aes-baseline \
	$(srcdir)/Penglai-sdk-TVM/demo/rv8-baseline/dhrystone/dhrystone-baseline \
	$(srcdir)/Penglai-sdk-TVM/demo/rv8-baseline/norx/norx-baseline \
	$(srcdir)/Penglai-sdk-TVM/demo/rv8-baseline/primes/primes-baseline \
	$(srcdir)/Penglai-sdk-TVM/demo/rv8-baseline/qsort/qsort-baseline \
	$(srcdir)/Penglai-sdk-TVM/demo/rv8-baseline/sha512/sha512-baseline \
	$(srcdir)/Penglai-sdk-TVM/demo/relay-page/relay-page \
	$(srcdir)/Penglai-sdk-TVM/demo/mem/mem \
	$(srcdir)/Penglai-sdk-TVM/demo/IPC/caller/caller \
	$(srcdir)/Penglai-sdk-TVM/demo/IPC/server/server \
	$(srcdir)/Penglai-sdk-TVM/demo/IPC/server1/server1 \
	$(srcdir)/Penglai-sdk-TVM/demo/IPC/test-caller/test-caller \
	$(srcdir)/Penglai-sdk-TVM/demo/FS/fshost/fshost \
	$(srcdir)/Penglai-sdk-TVM/demo/FS/testfs/testfs \
	$(srcdir)/Penglai-sdk-TVM/demo/FS/littlefs/lfs \
	$(srcdir)/Penglai-sdk-TVM/demo/test-stop/host/test-stop \
	$(srcdir)/Penglai-sdk-TVM/demo/test-stop/loop/loop \
	$(srcdir)/Penglai-sdk-TVM/demo/psa/psa_host/psahost \
	$(srcdir)/Penglai-sdk-TVM/demo/psa/psa_server/psa_server \
	$(srcdir)/Penglai-sdk-TVM/demo/psa/psa_client/psa_client \
	$(srcdir)/Penglai-sdk-TVM/demo/psa/psa_key_ladder/psa_key_ladder \
	$(srcdir)/Penglai-sdk-TVM/demo/psa/psa_crypto/psa_crypto \
	$(srcdir)/Penglai-sdk-TVM/demo/seperated_filesystem_simple/decouplefs_simple