#  TODO: subdir
all:
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C app
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C host

clean:
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C app clean
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C host clean
