all:
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  pe-agent
	# CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  test-attest
	# CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  test-create
	# CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  test-destroy
	# CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  test-pressure
	# CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  test-resume
	# CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  test-run
clean:
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  pe-agent clean
	# CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  test-attest clean
	# CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  test-create clean
	# CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  test-destroy clean
	# CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  test-pressure clean
	# CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  test-resume clean
	# CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  test-run clean