all:
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-share
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-sharer
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-sharee
clean:
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-share
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-sharer
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-sharee