all:
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-share
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-sharer
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-sharee
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-sharee-plus
clean:
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-share
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-sharer
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-sharee
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-sharee-plus