all:
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-inspector
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-inspectee
clean:
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-inspector clean
	CC=$(CC) LINK=$(LINK) AR=$(AR) make -C  case-inspectee clean